version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"

  # docker-compose is not supported by dependabot yet
  # - package-ecosystem: "docker"
  #   directory: "/"
  #   schedule:
  #     interval: "monthly"
