[tool.poetry]
name = "movie-ratings-streaming"
version = "0.2.0"
description = "Spark Structured Streaming data pipeline that processes movie ratings data in real-time"
authors = ["Guido Kosloff Gancedo <guidokosloff@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.12"
pyspark = "~3.5.4"
delta-spark = "~3.3.0"

[tool.poetry.group.dev.dependencies]
black = "~25.1.0"
ruff = "~0.9.4"
mypy = "~1.14.1"
isort = "~6.0.0"
confluent-kafka = {extras = ["avro", "schemaregistry"], version ="~2.8.0"}
requests = "~2.32.3"
fastavro = "~1.10.0"
pre-commit = "~4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py312']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
profile = "black"

[tool.coverage.run]
branch = true
source = ["movies_etl"]

[tool.coverage.report]
show_missing = true

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.ruff]
line-length = 120
