[tool.poetry]
name = "movie-ratings-streaming"
version = "0.1.1"
description = "Spark Structured Streaming + Kafka demo app"
authors = ["Guido Kosloff Gancedo <guidokosloff@gmail.com>"]
readme = "README.md"
packages = [{include = "movie_ratings_streaming"}]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"

[tool.poetry.group.dev.dependencies]
pyspark = "3.4.1"
delta-spark = "2.4.0"
black = "^23.7.0"
isort = "^5.12.0"
confluent-kafka = "^2.2.0"
requests = "^2.31.0"
fastavro = "^1.8.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
