stream:
  source_kafka_topic: movies.added
  sink_dir: file:///Users/gk/Git/spark-structured-streaming-example/data_lake/sink
  checkpoint_dir: file:///Users/gk/Git/spark-structured-streaming-example/data_lake/checkpoint
  trigger_processing_time: '10 seconds'
  output_mode: append
  nr_partitions_per_batch: 1

kafka:
  kafka.bootstrap.servers: kafka-staging-test.movies.com:9092
  startingOffsets: earliest
  kafka.security.protocol: SSL
  kafka.ssl.truststore.location: /Users/gk/Git/spark_structured_streaming_example/spark_structured_streaming_example/conf/kafka.client.truststore.jks
  kafka.ssl.truststore.password: XXXXXXXX
  kafka.ssl.keystore.location: /Users/gk/Git/spark-structured-streaming-example/spark_structured_streaming_example/conf/kafka.client.keystore.p12
  kafka.ssl.keystore.password: XXXXXXXX
  kafka.ssl.key.password: XXXXXXXX
